USE lv4_glazba;

INSERT INTO pjesme (naslov, autor, zanr, bpm, godina, raspolozenje) VALUES
('Blinding Lights',            'The Weeknd',                    'Synthwave',    171, 2020, 'Energetic'),
('Bohemian Rhapsody',          'Queen',                         'Rock',          72, 1975, 'Dramatic'),
('Bad Guy',                    'Billie Eilish',                  'Electropop',   135, 2019, 'Dark'),
('Shape of You',               'Ed Sheeran',                    'Pop',           96, 2017, 'Happy'),
('Hotel California',           'Eagles',                        'Rock',          74, 1976, 'Melancholic'),
('Levitating',                 'Dua Lipa',                      'Disco-Pop',    103, 2020, 'Cheerful'),
('Thunderstruck',              'AC/DC',                         'Hard Rock',    134, 1990, 'Powerful'),
('Stay',                       'The Kid LAROI & Justin Bieber', 'Pop',          170, 2021, 'Energetic'),
('Smells Like Teen Spirit',    'Nirvana',                       'Grunge',       117, 1991, 'Aggressive'),
('In the End',                 'Linkin Park',                   'Nu Metal',     105, 2000, 'Emotional'),
('Superstition',               'Stevie Wonder',                 'Funk',         101, 1972, 'Groovy'),
("Don't Stop Believin'",       'Journey',                       'Rock',         119, 1981, 'Inspirational'),
('Rolling in the Deep',        'Adele',                         'Soul',         105, 2011, 'Passionate'),
('Take Five',                  'Dave Brubeck',                  'Jazz',         174, 1959, 'Relaxed'),
('One More Time',              'Daft Punk',                     'House',        123, 2000, 'Festive'),
('Lose Yourself',              'Eminem',                        'Hip Hop',      171, 2002, 'Determined'),
('Dreams',                     'Fleetwood Mac',                 'Soft Rock',    120, 1977, 'Dreamy'),
('Master of Puppets',          'Metallica',                     'Thrash Metal', 212, 1986, 'Intense'),
('Uptown Funk',                'Mark Ronson ft. Bruno Mars',    'Funk',         115, 2014, 'Funky'),
('Billie Jean',                'Michael Jackson',               'Pop',          117, 1982, 'Danceable'),
('Mr. Brightside',             'The Killers',                   'Indie Rock',   148, 2004, 'Anthemic'),
('Starboy',                    'The Weeknd',                    'R&B',          186, 2016, 'Moody'),
('Another One Bites the Dust', 'Queen',                         'Funk Rock',    110, 1980, 'Confident'),
('Flowers',                    'Miley Cyrus',                   'Pop',          118, 2023, 'Empowering'),
('Highway to Hell',            'AC/DC',                         'Hard Rock',    116, 1979, 'Wild'),
("Sweet Child O' Mine",        "Guns N' Roses",                 'Hard Rock',    125, 1987, 'Romantic'),
('Humble',                     'Kendrick Lamar',                'Hip Hop',      150, 2017, 'Serious'),
('Seven Nation Army',          'The White Stripes',             'Garage Rock',  124, 2003, 'Gritty'),
('Wake Me Up',                 'Avicii',                        'EDM',          124, 2013, 'Uplifting'),
('Watermelon Sugar',           'Harry Styles',                  'Pop',           95, 2019, 'Summer Vibes');
